"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Operation:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _OperationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Operation.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OPERATION_UNSPECIFIED: _Operation.ValueType  # 0
    OPERATION_BACKUP: _Operation.ValueType  # 1
    OPERATION_CANCEL_BACKUP: _Operation.ValueType  # 2
    OPERATION_RECOVER_CONTAINERS: _Operation.ValueType  # 3
    OPERATION_START_AUTHENTICATION: _Operation.ValueType  # 4
    OPERATION_CANCEL_AUTHENTICATION: _Operation.ValueType  # 5
    OPERATION_SIGN_OUT: _Operation.ValueType  # 6
    OPERATION_APPLY_CONFIGURATION: _Operation.ValueType  # 7
    OPERATION_INSPECT_ARCHIVE: _Operation.ValueType  # 8
    OPERATION_EXTRACT_FILES: _Operation.ValueType  # 9

class Operation(_Operation, metaclass=_OperationEnumTypeWrapper): ...

OPERATION_UNSPECIFIED: Operation.ValueType  # 0
OPERATION_BACKUP: Operation.ValueType  # 1
OPERATION_CANCEL_BACKUP: Operation.ValueType  # 2
OPERATION_RECOVER_CONTAINERS: Operation.ValueType  # 3
OPERATION_START_AUTHENTICATION: Operation.ValueType  # 4
OPERATION_CANCEL_AUTHENTICATION: Operation.ValueType  # 5
OPERATION_SIGN_OUT: Operation.ValueType  # 6
OPERATION_APPLY_CONFIGURATION: Operation.ValueType  # 7
OPERATION_INSPECT_ARCHIVE: Operation.ValueType  # 8
OPERATION_EXTRACT_FILES: Operation.ValueType  # 9
Global___Operation: _TypeAlias = Operation  # noqa: Y015

class _JobState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _JobStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_JobState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    JOB_STATE_UNSPECIFIED: _JobState.ValueType  # 0
    JOB_STATE_QUEUED: _JobState.ValueType  # 1
    JOB_STATE_RUNNING: _JobState.ValueType  # 2
    JOB_STATE_SUCCEEDED: _JobState.ValueType  # 3
    JOB_STATE_FAILED: _JobState.ValueType  # 4
    JOB_STATE_INTERRUPTED: _JobState.ValueType  # 5
    JOB_STATE_CANCELLED: _JobState.ValueType  # 6

class JobState(_JobState, metaclass=_JobStateEnumTypeWrapper): ...

JOB_STATE_UNSPECIFIED: JobState.ValueType  # 0
JOB_STATE_QUEUED: JobState.ValueType  # 1
JOB_STATE_RUNNING: JobState.ValueType  # 2
JOB_STATE_SUCCEEDED: JobState.ValueType  # 3
JOB_STATE_FAILED: JobState.ValueType  # 4
JOB_STATE_INTERRUPTED: JobState.ValueType  # 5
JOB_STATE_CANCELLED: JobState.ValueType  # 6
Global___JobState: _TypeAlias = JobState  # noqa: Y015

@_typing.final
class GetStatusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetStatusRequest: _TypeAlias = GetStatusRequest  # noqa: Y015

@_typing.final
class GetStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PHASE_FIELD_NUMBER: _builtins.int
    RUNNING_FIELD_NUMBER: _builtins.int
    RECOVERY_PENDING_FIELD_NUMBER: _builtins.int
    LAST_SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    ACCOUNT_STATE_FIELD_NUMBER: _builtins.int
    ACCOUNT_EMAIL_FIELD_NUMBER: _builtins.int
    AUTHENTICATION_URL_FIELD_NUMBER: _builtins.int
    TRANSFER_PHASE_FIELD_NUMBER: _builtins.int
    TRANSFER_FILE_FIELD_NUMBER: _builtins.int
    TRANSFER_ELAPSED_SECONDS_FIELD_NUMBER: _builtins.int
    PENDING_CONFIGURATION_FIELD_NUMBER: _builtins.int
    ACCOUNT_ERROR_FIELD_NUMBER: _builtins.int
    ERROR_CODE_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    BACKENDS_FIELD_NUMBER: _builtins.int
    phase: _builtins.str
    running: _builtins.bool
    recovery_pending: _builtins.bool
    last_success: _builtins.str
    error: _builtins.str
    account_state: _builtins.str
    account_email: _builtins.str
    authentication_url: _builtins.str
    transfer_phase: _builtins.str
    transfer_file: _builtins.str
    transfer_elapsed_seconds: _builtins.int
    pending_configuration: _builtins.bool
    account_error: _builtins.str
    error_code: _builtins.str
    started_at: _builtins.str
    @_builtins.property
    def backends(self) -> _containers.RepeatedCompositeFieldContainer[Global___BackendStatus]: ...
    def __init__(
        self,
        *,
        phase: _builtins.str = ...,
        running: _builtins.bool = ...,
        recovery_pending: _builtins.bool = ...,
        last_success: _builtins.str = ...,
        error: _builtins.str = ...,
        account_state: _builtins.str = ...,
        account_email: _builtins.str = ...,
        authentication_url: _builtins.str = ...,
        transfer_phase: _builtins.str = ...,
        transfer_file: _builtins.str = ...,
        transfer_elapsed_seconds: _builtins.int = ...,
        pending_configuration: _builtins.bool = ...,
        account_error: _builtins.str = ...,
        error_code: _builtins.str = ...,
        started_at: _builtins.str = ...,
        backends: _abc.Iterable[Global___BackendStatus] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_email", b"account_email", "account_error", b"account_error", "account_state", b"account_state", "authentication_url", b"authentication_url", "backends", b"backends", "error", b"error", "error_code", b"error_code", "last_success", b"last_success", "pending_configuration", b"pending_configuration", "phase", b"phase", "recovery_pending", b"recovery_pending", "running", b"running", "started_at", b"started_at", "transfer_elapsed_seconds", b"transfer_elapsed_seconds", "transfer_file", b"transfer_file", "transfer_phase", b"transfer_phase"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetStatusResponse: _TypeAlias = GetStatusResponse  # noqa: Y015

@_typing.final
class BackendStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    AUTHENTICATION_URL_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    TRANSFER_PHASE_FIELD_NUMBER: _builtins.int
    TRANSFER_FILE_FIELD_NUMBER: _builtins.int
    TRANSFER_ELAPSED_SECONDS_FIELD_NUMBER: _builtins.int
    TRANSFER_PERCENT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    kind: _builtins.str
    name: _builtins.str
    enabled: _builtins.bool
    state: _builtins.str
    email: _builtins.str
    authentication_url: _builtins.str
    error: _builtins.str
    transfer_phase: _builtins.str
    transfer_file: _builtins.str
    transfer_elapsed_seconds: _builtins.int
    transfer_percent: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        kind: _builtins.str = ...,
        name: _builtins.str = ...,
        enabled: _builtins.bool = ...,
        state: _builtins.str = ...,
        email: _builtins.str = ...,
        authentication_url: _builtins.str = ...,
        error: _builtins.str = ...,
        transfer_phase: _builtins.str = ...,
        transfer_file: _builtins.str = ...,
        transfer_elapsed_seconds: _builtins.int = ...,
        transfer_percent: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_transfer_percent", b"_transfer_percent", "transfer_percent", b"transfer_percent"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_transfer_percent", b"_transfer_percent", "authentication_url", b"authentication_url", "email", b"email", "enabled", b"enabled", "error", b"error", "id", b"id", "kind", b"kind", "name", b"name", "state", b"state", "transfer_elapsed_seconds", b"transfer_elapsed_seconds", "transfer_file", b"transfer_file", "transfer_percent", b"transfer_percent", "transfer_phase", b"transfer_phase"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__transfer_percent: _TypeAlias = _typing.Literal["transfer_percent"]  # noqa: Y015
    _WhichOneofArgType__transfer_percent: _TypeAlias = _typing.Literal["_transfer_percent", b"_transfer_percent"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__transfer_percent) -> _WhichOneofReturnType__transfer_percent | None: ...

Global___BackendStatus: _TypeAlias = BackendStatus  # noqa: Y015

@_typing.final
class Destination(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    ROOT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    kind: _builtins.str
    name: _builtins.str
    enabled: _builtins.bool
    root: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        kind: _builtins.str = ...,
        name: _builtins.str = ...,
        enabled: _builtins.bool = ...,
        root: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "id", b"id", "kind", b"kind", "name", b"name", "root", b"root"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Destination: _TypeAlias = Destination  # noqa: Y015

@_typing.final
class Configuration(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    SCHEDULE_HOUR_FIELD_NUMBER: _builtins.int
    SCHEDULE_MINUTE_FIELD_NUMBER: _builtins.int
    MINIMUM_FREE_BYTES_FIELD_NUMBER: _builtins.int
    CONTAINER_STOP_TIMEOUT_SECONDS_FIELD_NUMBER: _builtins.int
    COMMAND_TIMEOUT_SECONDS_FIELD_NUMBER: _builtins.int
    TRANSFER_TIMEOUT_SECONDS_FIELD_NUMBER: _builtins.int
    STAGING_PATH_FIELD_NUMBER: _builtins.int
    REMOTE_PATH_FIELD_NUMBER: _builtins.int
    DESTINATIONS_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    instance_id: _builtins.str
    schedule_hour: _builtins.int
    schedule_minute: _builtins.int
    minimum_free_bytes: _builtins.int
    container_stop_timeout_seconds: _builtins.int
    command_timeout_seconds: _builtins.int
    transfer_timeout_seconds: _builtins.int
    staging_path: _builtins.str
    remote_path: _builtins.str
    @_builtins.property
    def destinations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Destination]: ...
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        instance_id: _builtins.str = ...,
        schedule_hour: _builtins.int = ...,
        schedule_minute: _builtins.int = ...,
        minimum_free_bytes: _builtins.int = ...,
        container_stop_timeout_seconds: _builtins.int = ...,
        command_timeout_seconds: _builtins.int = ...,
        transfer_timeout_seconds: _builtins.int = ...,
        staging_path: _builtins.str = ...,
        remote_path: _builtins.str = ...,
        destinations: _abc.Iterable[Global___Destination] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command_timeout_seconds", b"command_timeout_seconds", "container_stop_timeout_seconds", b"container_stop_timeout_seconds", "destinations", b"destinations", "enabled", b"enabled", "instance_id", b"instance_id", "minimum_free_bytes", b"minimum_free_bytes", "remote_path", b"remote_path", "schedule_hour", b"schedule_hour", "schedule_minute", b"schedule_minute", "staging_path", b"staging_path", "transfer_timeout_seconds", b"transfer_timeout_seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Configuration: _TypeAlias = Configuration  # noqa: Y015

@_typing.final
class GetConfigurationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetConfigurationRequest: _TypeAlias = GetConfigurationRequest  # noqa: Y015

@_typing.final
class GetConfigurationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIGURATION_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    revision: _builtins.str
    @_builtins.property
    def configuration(self) -> Global___Configuration: ...
    def __init__(
        self,
        *,
        configuration: Global___Configuration | None = ...,
        revision: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["configuration", b"configuration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["configuration", b"configuration", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetConfigurationResponse: _TypeAlias = GetConfigurationResponse  # noqa: Y015

@_typing.final
class SaveConfigurationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIGURATION_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    revision: _builtins.str
    @_builtins.property
    def configuration(self) -> Global___Configuration: ...
    def __init__(
        self,
        *,
        configuration: Global___Configuration | None = ...,
        revision: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["configuration", b"configuration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["configuration", b"configuration", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SaveConfigurationRequest: _TypeAlias = SaveConfigurationRequest  # noqa: Y015

@_typing.final
class SaveConfigurationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    revision: _builtins.str
    def __init__(
        self,
        *,
        revision: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SaveConfigurationResponse: _TypeAlias = SaveConfigurationResponse  # noqa: Y015

@_typing.final
class BackupSet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    PATHS_FIELD_NUMBER: _builtins.int
    EXCLUSIONS_FIELD_NUMBER: _builtins.int
    STOP_ALL_CONTAINERS_FIELD_NUMBER: _builtins.int
    LOCAL_KEEP_FIELD_NUMBER: _builtins.int
    REMOTE_KEEP_FIELD_NUMBER: _builtins.int
    CONTAINER_IDS_FIELD_NUMBER: _builtins.int
    COMPOSE_PROJECTS_FIELD_NUMBER: _builtins.int
    COMPOSE_APPLICATIONS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    enabled: _builtins.bool
    stop_all_containers: _builtins.bool
    local_keep: _builtins.int
    remote_keep: _builtins.int
    @_builtins.property
    def paths(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def exclusions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def container_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def compose_projects(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def compose_applications(self) -> _containers.RepeatedCompositeFieldContainer[Global___ComposeApplication]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        enabled: _builtins.bool = ...,
        paths: _abc.Iterable[_builtins.str] | None = ...,
        exclusions: _abc.Iterable[_builtins.str] | None = ...,
        stop_all_containers: _builtins.bool = ...,
        local_keep: _builtins.int = ...,
        remote_keep: _builtins.int = ...,
        container_ids: _abc.Iterable[_builtins.str] | None = ...,
        compose_projects: _abc.Iterable[_builtins.str] | None = ...,
        compose_applications: _abc.Iterable[Global___ComposeApplication] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compose_applications", b"compose_applications", "compose_projects", b"compose_projects", "container_ids", b"container_ids", "enabled", b"enabled", "exclusions", b"exclusions", "id", b"id", "local_keep", b"local_keep", "name", b"name", "paths", b"paths", "remote_keep", b"remote_keep", "stop_all_containers", b"stop_all_containers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BackupSet: _TypeAlias = BackupSet  # noqa: Y015

@_typing.final
class ComposeApplication(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    DEFINITIONS_FIELD_NUMBER: _builtins.int
    ENV_FILES_FIELD_NUMBER: _builtins.int
    SECRET_FILES_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    @_builtins.property
    def definitions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def env_files(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def secret_files(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        definitions: _abc.Iterable[_builtins.str] | None = ...,
        env_files: _abc.Iterable[_builtins.str] | None = ...,
        secret_files: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["definitions", b"definitions", "env_files", b"env_files", "project", b"project", "secret_files", b"secret_files"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ComposeApplication: _TypeAlias = ComposeApplication  # noqa: Y015

@_typing.final
class ListSetsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListSetsRequest: _TypeAlias = ListSetsRequest  # noqa: Y015

@_typing.final
class ListSetsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SETS_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    revision: _builtins.str
    @_builtins.property
    def sets(self) -> _containers.RepeatedCompositeFieldContainer[Global___BackupSet]: ...
    def __init__(
        self,
        *,
        sets: _abc.Iterable[Global___BackupSet] | None = ...,
        revision: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sets", b"sets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListSetsResponse: _TypeAlias = ListSetsResponse  # noqa: Y015

@_typing.final
class SaveSetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SET_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    revision: _builtins.str
    @_builtins.property
    def set(self) -> Global___BackupSet: ...
    def __init__(
        self,
        *,
        set: Global___BackupSet | None = ...,
        revision: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["set", b"set"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "set", b"set"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SaveSetRequest: _TypeAlias = SaveSetRequest  # noqa: Y015

@_typing.final
class SaveSetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SET_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def set(self) -> Global___BackupSet: ...
    def __init__(
        self,
        *,
        set: Global___BackupSet | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["set", b"set"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["set", b"set"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SaveSetResponse: _TypeAlias = SaveSetResponse  # noqa: Y015

@_typing.final
class DeleteSetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    revision: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        revision: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteSetRequest: _TypeAlias = DeleteSetRequest  # noqa: Y015

@_typing.final
class DeleteSetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteSetResponse: _TypeAlias = DeleteSetResponse  # noqa: Y015

@_typing.final
class Job(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    OPERATION_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    SEQUENCE_FIELD_NUMBER: _builtins.int
    FAILURE_CODE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    operation: Global___Operation.ValueType
    state: Global___JobState.ValueType
    message: _builtins.str
    sequence: _builtins.int
    failure_code: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        operation: Global___Operation.ValueType = ...,
        state: Global___JobState.ValueType = ...,
        message: _builtins.str = ...,
        sequence: _builtins.int = ...,
        failure_code: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure_code", b"failure_code", "id", b"id", "message", b"message", "operation", b"operation", "sequence", b"sequence", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Job: _TypeAlias = Job  # noqa: Y015

@_typing.final
class StartOperationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OPERATION_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    INSPECT_ARCHIVE_FIELD_NUMBER: _builtins.int
    EXTRACT_FILES_FIELD_NUMBER: _builtins.int
    DESTINATION_ID_FIELD_NUMBER: _builtins.int
    operation: Global___Operation.ValueType
    request_id: _builtins.str
    destination_id: _builtins.str
    @_builtins.property
    def inspect_archive(self) -> Global___ArchiveReference: ...
    @_builtins.property
    def extract_files(self) -> Global___FileExtraction: ...
    def __init__(
        self,
        *,
        operation: Global___Operation.ValueType = ...,
        request_id: _builtins.str = ...,
        inspect_archive: Global___ArchiveReference | None = ...,
        extract_files: Global___FileExtraction | None = ...,
        destination_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["extract_files", b"extract_files", "inspect_archive", b"inspect_archive", "parameters", b"parameters"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_id", b"destination_id", "extract_files", b"extract_files", "inspect_archive", b"inspect_archive", "operation", b"operation", "parameters", b"parameters", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_parameters: _TypeAlias = _typing.Literal["inspect_archive", "extract_files"]  # noqa: Y015
    _WhichOneofArgType_parameters: _TypeAlias = _typing.Literal["parameters", b"parameters"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_parameters) -> _WhichOneofReturnType_parameters | None: ...

Global___StartOperationRequest: _TypeAlias = StartOperationRequest  # noqa: Y015

@_typing.final
class StartOperationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def job(self) -> Global___Job: ...
    def __init__(
        self,
        *,
        job: Global___Job | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartOperationResponse: _TypeAlias = StartOperationResponse  # noqa: Y015

@_typing.final
class GetJobRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetJobRequest: _TypeAlias = GetJobRequest  # noqa: Y015

@_typing.final
class GetJobResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def job(self) -> Global___Job: ...
    def __init__(
        self,
        *,
        job: Global___Job | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetJobResponse: _TypeAlias = GetJobResponse  # noqa: Y015

@_typing.final
class WatchJobRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    AFTER_SEQUENCE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    after_sequence: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        after_sequence: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after_sequence", b"after_sequence", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchJobRequest: _TypeAlias = WatchJobRequest  # noqa: Y015

@_typing.final
class WatchJobResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def job(self) -> Global___Job: ...
    def __init__(
        self,
        *,
        job: Global___Job | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchJobResponse: _TypeAlias = WatchJobResponse  # noqa: Y015

@_typing.final
class BrowseDirectoriesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SHARED_FOLDER_ID_FIELD_NUMBER: _builtins.int
    RELATIVE_PATH_FIELD_NUMBER: _builtins.int
    shared_folder_id: _builtins.str
    relative_path: _builtins.str
    def __init__(
        self,
        *,
        shared_folder_id: _builtins.str = ...,
        relative_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["relative_path", b"relative_path", "shared_folder_id", b"shared_folder_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BrowseDirectoriesRequest: _TypeAlias = BrowseDirectoriesRequest  # noqa: Y015

@_typing.final
class Directory(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    RELATIVE_PATH_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    relative_path: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        relative_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "relative_path", b"relative_path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Directory: _TypeAlias = Directory  # noqa: Y015

@_typing.final
class BrowseDirectoriesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DIRECTORIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def directories(self) -> _containers.RepeatedCompositeFieldContainer[Global___Directory]: ...
    def __init__(
        self,
        *,
        directories: _abc.Iterable[Global___Directory] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["directories", b"directories"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BrowseDirectoriesResponse: _TypeAlias = BrowseDirectoriesResponse  # noqa: Y015

@_typing.final
class ListContainersRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListContainersRequest: _TypeAlias = ListContainersRequest  # noqa: Y015

@_typing.final
class Container(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    COMPOSE_PROJECT_FIELD_NUMBER: _builtins.int
    RUNNING_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    compose_project: _builtins.str
    running: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        compose_project: _builtins.str = ...,
        running: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compose_project", b"compose_project", "id", b"id", "name", b"name", "running", b"running"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Container: _TypeAlias = Container  # noqa: Y015

@_typing.final
class ListContainersResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTAINERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def containers(self) -> _containers.RepeatedCompositeFieldContainer[Global___Container]: ...
    def __init__(
        self,
        *,
        containers: _abc.Iterable[Global___Container] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["containers", b"containers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListContainersResponse: _TypeAlias = ListContainersResponse  # noqa: Y015

@_typing.final
class BrowseBackupsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    SET_ID_FIELD_NUMBER: _builtins.int
    DESTINATION_ID_FIELD_NUMBER: _builtins.int
    instance_id: _builtins.str
    set_id: _builtins.str
    destination_id: _builtins.str
    def __init__(
        self,
        *,
        instance_id: _builtins.str | None = ...,
        set_id: _builtins.str | None = ...,
        destination_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_instance_id", b"_instance_id", "_set_id", b"_set_id", "instance_id", b"instance_id", "set_id", b"set_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_instance_id", b"_instance_id", "_set_id", b"_set_id", "destination_id", b"destination_id", "instance_id", b"instance_id", "set_id", b"set_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__instance_id: _TypeAlias = _typing.Literal["instance_id"]  # noqa: Y015
    _WhichOneofArgType__instance_id: _TypeAlias = _typing.Literal["_instance_id", b"_instance_id"]  # noqa: Y015
    _WhichOneofReturnType__set_id: _TypeAlias = _typing.Literal["set_id"]  # noqa: Y015
    _WhichOneofArgType__set_id: _TypeAlias = _typing.Literal["_set_id", b"_set_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__instance_id) -> _WhichOneofReturnType__instance_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__set_id) -> _WhichOneofReturnType__set_id | None: ...

Global___BrowseBackupsRequest: _TypeAlias = BrowseBackupsRequest  # noqa: Y015

@_typing.final
class BackupEntry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DIRECTORY_FIELD_NUMBER: _builtins.int
    COMPLETE_PAIR_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    directory: _builtins.bool
    complete_pair: _builtins.bool
    size: _builtins.int
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        directory: _builtins.bool = ...,
        complete_pair: _builtins.bool = ...,
        size: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_size", b"_size", "size", b"size"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_size", b"_size", "complete_pair", b"complete_pair", "directory", b"directory", "name", b"name", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__size: _TypeAlias = _typing.Literal["size"]  # noqa: Y015
    _WhichOneofArgType__size: _TypeAlias = _typing.Literal["_size", b"_size"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__size) -> _WhichOneofReturnType__size | None: ...

Global___BackupEntry: _TypeAlias = BackupEntry  # noqa: Y015

@_typing.final
class BrowseBackupsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    FOREIGN_INSTANCE_FIELD_NUMBER: _builtins.int
    foreign_instance: _builtins.bool
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___BackupEntry]: ...
    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___BackupEntry] | None = ...,
        foreign_instance: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries", "foreign_instance", b"foreign_instance"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BrowseBackupsResponse: _TypeAlias = BrowseBackupsResponse  # noqa: Y015

@_typing.final
class ArchiveReference(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    SET_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESTINATION_ID_FIELD_NUMBER: _builtins.int
    instance_id: _builtins.str
    set_id: _builtins.str
    name: _builtins.str
    destination_id: _builtins.str
    def __init__(
        self,
        *,
        instance_id: _builtins.str = ...,
        set_id: _builtins.str = ...,
        name: _builtins.str = ...,
        destination_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_id", b"destination_id", "instance_id", b"instance_id", "name", b"name", "set_id", b"set_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArchiveReference: _TypeAlias = ArchiveReference  # noqa: Y015

@_typing.final
class FileExtraction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSPECTION_ID_FIELD_NUMBER: _builtins.int
    PATHS_FIELD_NUMBER: _builtins.int
    DESTINATION_FIELD_NUMBER: _builtins.int
    inspection_id: _builtins.str
    destination: _builtins.str
    @_builtins.property
    def paths(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        inspection_id: _builtins.str = ...,
        paths: _abc.Iterable[_builtins.str] | None = ...,
        destination: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination", b"destination", "inspection_id", b"inspection_id", "paths", b"paths"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileExtraction: _TypeAlias = FileExtraction  # noqa: Y015

@_typing.final
class GetArchiveRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSPECTION_ID_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    inspection_id: _builtins.str
    offset: _builtins.int
    def __init__(
        self,
        *,
        inspection_id: _builtins.str = ...,
        offset: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["inspection_id", b"inspection_id", "offset", b"offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetArchiveRequest: _TypeAlias = GetArchiveRequest  # noqa: Y015

@_typing.final
class ArchiveMember(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    LINK_TARGET_FIELD_NUMBER: _builtins.int
    ISSUE_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    kind: _builtins.str
    size: _builtins.int
    link_target: _builtins.str
    issue: _builtins.str
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        kind: _builtins.str = ...,
        size: _builtins.int = ...,
        link_target: _builtins.str = ...,
        issue: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["issue", b"issue", "kind", b"kind", "link_target", b"link_target", "path", b"path", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArchiveMember: _TypeAlias = ArchiveMember  # noqa: Y015

@_typing.final
class GetArchiveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MEMBERS_FIELD_NUMBER: _builtins.int
    TOTAL_FIELD_NUMBER: _builtins.int
    NEXT_OFFSET_FIELD_NUMBER: _builtins.int
    COMPOSE_FIELD_NUMBER: _builtins.int
    total: _builtins.int
    next_offset: _builtins.int
    @_builtins.property
    def members(self) -> _containers.RepeatedCompositeFieldContainer[Global___ArchiveMember]: ...
    @_builtins.property
    def compose(self) -> _containers.RepeatedCompositeFieldContainer[Global___ComposeProjectSnapshot]: ...
    def __init__(
        self,
        *,
        members: _abc.Iterable[Global___ArchiveMember] | None = ...,
        total: _builtins.int = ...,
        next_offset: _builtins.int = ...,
        compose: _abc.Iterable[Global___ComposeProjectSnapshot] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compose", b"compose", "members", b"members", "next_offset", b"next_offset", "total", b"total"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetArchiveResponse: _TypeAlias = GetArchiveResponse  # noqa: Y015

@_typing.final
class ComposeProjectSnapshot(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    DEFINITIONS_FIELD_NUMBER: _builtins.int
    ENV_FILES_FIELD_NUMBER: _builtins.int
    SECRET_FILES_FIELD_NUMBER: _builtins.int
    SERVICES_FIELD_NUMBER: _builtins.int
    project: _builtins.str
    @_builtins.property
    def definitions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def env_files(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def secret_files(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def services(self) -> _containers.RepeatedCompositeFieldContainer[Global___ComposeServiceSnapshot]: ...
    def __init__(
        self,
        *,
        project: _builtins.str = ...,
        definitions: _abc.Iterable[_builtins.str] | None = ...,
        env_files: _abc.Iterable[_builtins.str] | None = ...,
        secret_files: _abc.Iterable[_builtins.str] | None = ...,
        services: _abc.Iterable[Global___ComposeServiceSnapshot] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["definitions", b"definitions", "env_files", b"env_files", "project", b"project", "secret_files", b"secret_files", "services", b"services"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ComposeProjectSnapshot: _TypeAlias = ComposeProjectSnapshot  # noqa: Y015

@_typing.final
class ComposeServiceSnapshot(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_FIELD_NUMBER: _builtins.int
    IMAGE_FIELD_NUMBER: _builtins.int
    PINNED_FIELD_NUMBER: _builtins.int
    REPLICAS_FIELD_NUMBER: _builtins.int
    BINDS_FIELD_NUMBER: _builtins.int
    service: _builtins.str
    image: _builtins.str
    pinned: _builtins.str
    replicas: _builtins.int
    @_builtins.property
    def binds(self) -> _containers.RepeatedCompositeFieldContainer[Global___ComposeBindSnapshot]: ...
    def __init__(
        self,
        *,
        service: _builtins.str = ...,
        image: _builtins.str = ...,
        pinned: _builtins.str = ...,
        replicas: _builtins.int = ...,
        binds: _abc.Iterable[Global___ComposeBindSnapshot] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binds", b"binds", "image", b"image", "pinned", b"pinned", "replicas", b"replicas", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ComposeServiceSnapshot: _TypeAlias = ComposeServiceSnapshot  # noqa: Y015

@_typing.final
class ComposeBindSnapshot(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FIELD_NUMBER: _builtins.int
    TARGET_FIELD_NUMBER: _builtins.int
    READ_ONLY_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    target: _builtins.str
    read_only: _builtins.bool
    def __init__(
        self,
        *,
        source: _builtins.str = ...,
        target: _builtins.str = ...,
        read_only: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["read_only", b"read_only", "source", b"source", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ComposeBindSnapshot: _TypeAlias = ComposeBindSnapshot  # noqa: Y015

@_typing.final
class CancelJobRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelJobRequest: _TypeAlias = CancelJobRequest  # noqa: Y015

@_typing.final
class CancelJobResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def job(self) -> Global___Job: ...
    def __init__(
        self,
        *,
        job: Global___Job | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelJobResponse: _TypeAlias = CancelJobResponse  # noqa: Y015

@_typing.final
class PreviewExtractionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXTRACTION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def extraction(self) -> Global___FileExtraction: ...
    def __init__(
        self,
        *,
        extraction: Global___FileExtraction | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["extraction", b"extraction"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extraction", b"extraction"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PreviewExtractionRequest: _TypeAlias = PreviewExtractionRequest  # noqa: Y015

@_typing.final
class PreviewExtractionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    REQUIRED_BYTES_FIELD_NUMBER: _builtins.int
    INCLUDED_DEPENDENCIES_FIELD_NUMBER: _builtins.int
    DESTINATION_FIELD_NUMBER: _builtins.int
    entries: _builtins.int
    required_bytes: _builtins.int
    destination: _builtins.str
    @_builtins.property
    def included_dependencies(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        entries: _builtins.int = ...,
        required_bytes: _builtins.int = ...,
        included_dependencies: _abc.Iterable[_builtins.str] | None = ...,
        destination: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination", b"destination", "entries", b"entries", "included_dependencies", b"included_dependencies", "required_bytes", b"required_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PreviewExtractionResponse: _TypeAlias = PreviewExtractionResponse  # noqa: Y015

@_typing.final
class ReleaseArchiveRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSPECTION_ID_FIELD_NUMBER: _builtins.int
    inspection_id: _builtins.str
    def __init__(
        self,
        *,
        inspection_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["inspection_id", b"inspection_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReleaseArchiveRequest: _TypeAlias = ReleaseArchiveRequest  # noqa: Y015

@_typing.final
class ReleaseArchiveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReleaseArchiveResponse: _TypeAlias = ReleaseArchiveResponse  # noqa: Y015

@_typing.final
class ListArchivesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListArchivesRequest: _TypeAlias = ListArchivesRequest  # noqa: Y015

@_typing.final
class CachedArchive(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSPECTION_ID_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    READY_FIELD_NUMBER: _builtins.int
    inspection_id: _builtins.str
    ready: _builtins.bool
    @_builtins.property
    def source(self) -> Global___ArchiveReference: ...
    def __init__(
        self,
        *,
        inspection_id: _builtins.str = ...,
        source: Global___ArchiveReference | None = ...,
        ready: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["source", b"source"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["inspection_id", b"inspection_id", "ready", b"ready", "source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CachedArchive: _TypeAlias = CachedArchive  # noqa: Y015

@_typing.final
class ListArchivesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ARCHIVES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def archives(self) -> _containers.RepeatedCompositeFieldContainer[Global___CachedArchive]: ...
    def __init__(
        self,
        *,
        archives: _abc.Iterable[Global___CachedArchive] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["archives", b"archives"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListArchivesResponse: _TypeAlias = ListArchivesResponse  # noqa: Y015

@_typing.final
class BrokerRequest(_message.Message):
    """Private broker transport uses the same generated messages as the public API."""

    DESCRIPTOR: _descriptor.Descriptor

    ACTOR_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    CONFIGURATION_FIELD_NUMBER: _builtins.int
    SAVE_CONFIGURATION_FIELD_NUMBER: _builtins.int
    SETS_FIELD_NUMBER: _builtins.int
    SAVE_SET_FIELD_NUMBER: _builtins.int
    DELETE_SET_FIELD_NUMBER: _builtins.int
    START_OPERATION_FIELD_NUMBER: _builtins.int
    JOB_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    DIRECTORIES_FIELD_NUMBER: _builtins.int
    CONTAINERS_FIELD_NUMBER: _builtins.int
    BACKUPS_FIELD_NUMBER: _builtins.int
    ARCHIVE_FIELD_NUMBER: _builtins.int
    CANCEL_JOB_FIELD_NUMBER: _builtins.int
    PREVIEW_EXTRACTION_FIELD_NUMBER: _builtins.int
    RELEASE_ARCHIVE_FIELD_NUMBER: _builtins.int
    LIST_ARCHIVES_FIELD_NUMBER: _builtins.int
    actor: _builtins.str
    @_builtins.property
    def status(self) -> Global___GetStatusRequest: ...
    @_builtins.property
    def configuration(self) -> Global___GetConfigurationRequest: ...
    @_builtins.property
    def save_configuration(self) -> Global___SaveConfigurationRequest: ...
    @_builtins.property
    def sets(self) -> Global___ListSetsRequest: ...
    @_builtins.property
    def save_set(self) -> Global___SaveSetRequest: ...
    @_builtins.property
    def delete_set(self) -> Global___DeleteSetRequest: ...
    @_builtins.property
    def start_operation(self) -> Global___StartOperationRequest: ...
    @_builtins.property
    def job(self) -> Global___GetJobRequest: ...
    @_builtins.property
    def events(self) -> Global___WatchJobRequest: ...
    @_builtins.property
    def directories(self) -> Global___BrowseDirectoriesRequest: ...
    @_builtins.property
    def containers(self) -> Global___ListContainersRequest: ...
    @_builtins.property
    def backups(self) -> Global___BrowseBackupsRequest: ...
    @_builtins.property
    def archive(self) -> Global___GetArchiveRequest: ...
    @_builtins.property
    def cancel_job(self) -> Global___CancelJobRequest: ...
    @_builtins.property
    def preview_extraction(self) -> Global___PreviewExtractionRequest: ...
    @_builtins.property
    def release_archive(self) -> Global___ReleaseArchiveRequest: ...
    @_builtins.property
    def list_archives(self) -> Global___ListArchivesRequest: ...
    def __init__(
        self,
        *,
        actor: _builtins.str = ...,
        status: Global___GetStatusRequest | None = ...,
        configuration: Global___GetConfigurationRequest | None = ...,
        save_configuration: Global___SaveConfigurationRequest | None = ...,
        sets: Global___ListSetsRequest | None = ...,
        save_set: Global___SaveSetRequest | None = ...,
        delete_set: Global___DeleteSetRequest | None = ...,
        start_operation: Global___StartOperationRequest | None = ...,
        job: Global___GetJobRequest | None = ...,
        events: Global___WatchJobRequest | None = ...,
        directories: Global___BrowseDirectoriesRequest | None = ...,
        containers: Global___ListContainersRequest | None = ...,
        backups: Global___BrowseBackupsRequest | None = ...,
        archive: Global___GetArchiveRequest | None = ...,
        cancel_job: Global___CancelJobRequest | None = ...,
        preview_extraction: Global___PreviewExtractionRequest | None = ...,
        release_archive: Global___ReleaseArchiveRequest | None = ...,
        list_archives: Global___ListArchivesRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["archive", b"archive", "backups", b"backups", "cancel_job", b"cancel_job", "configuration", b"configuration", "containers", b"containers", "delete_set", b"delete_set", "directories", b"directories", "events", b"events", "job", b"job", "list_archives", b"list_archives", "preview_extraction", b"preview_extraction", "release_archive", b"release_archive", "request", b"request", "save_configuration", b"save_configuration", "save_set", b"save_set", "sets", b"sets", "start_operation", b"start_operation", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "archive", b"archive", "backups", b"backups", "cancel_job", b"cancel_job", "configuration", b"configuration", "containers", b"containers", "delete_set", b"delete_set", "directories", b"directories", "events", b"events", "job", b"job", "list_archives", b"list_archives", "preview_extraction", b"preview_extraction", "release_archive", b"release_archive", "request", b"request", "save_configuration", b"save_configuration", "save_set", b"save_set", "sets", b"sets", "start_operation", b"start_operation", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_request: _TypeAlias = _typing.Literal["status", "configuration", "save_configuration", "sets", "save_set", "delete_set", "start_operation", "job", "events", "directories", "containers", "backups", "archive", "cancel_job", "preview_extraction", "release_archive", "list_archives"]  # noqa: Y015
    _WhichOneofArgType_request: _TypeAlias = _typing.Literal["request", b"request"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_request) -> _WhichOneofReturnType_request | None: ...

Global___BrokerRequest: _TypeAlias = BrokerRequest  # noqa: Y015

@_typing.final
class BrokerResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    CONFIGURATION_FIELD_NUMBER: _builtins.int
    SAVE_CONFIGURATION_FIELD_NUMBER: _builtins.int
    SETS_FIELD_NUMBER: _builtins.int
    SAVE_SET_FIELD_NUMBER: _builtins.int
    DELETE_SET_FIELD_NUMBER: _builtins.int
    START_OPERATION_FIELD_NUMBER: _builtins.int
    JOB_FIELD_NUMBER: _builtins.int
    DIRECTORIES_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    CONTAINERS_FIELD_NUMBER: _builtins.int
    BACKUPS_FIELD_NUMBER: _builtins.int
    ARCHIVE_FIELD_NUMBER: _builtins.int
    CANCEL_JOB_FIELD_NUMBER: _builtins.int
    PREVIEW_EXTRACTION_FIELD_NUMBER: _builtins.int
    RELEASE_ARCHIVE_FIELD_NUMBER: _builtins.int
    LIST_ARCHIVES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def status(self) -> Global___GetStatusResponse: ...
    @_builtins.property
    def configuration(self) -> Global___GetConfigurationResponse: ...
    @_builtins.property
    def save_configuration(self) -> Global___SaveConfigurationResponse: ...
    @_builtins.property
    def sets(self) -> Global___ListSetsResponse: ...
    @_builtins.property
    def save_set(self) -> Global___SaveSetResponse: ...
    @_builtins.property
    def delete_set(self) -> Global___DeleteSetResponse: ...
    @_builtins.property
    def start_operation(self) -> Global___StartOperationResponse: ...
    @_builtins.property
    def job(self) -> Global___GetJobResponse: ...
    @_builtins.property
    def directories(self) -> Global___BrowseDirectoriesResponse: ...
    @_builtins.property
    def events(self) -> Global___JobEvents: ...
    @_builtins.property
    def error(self) -> Global___BrokerError: ...
    @_builtins.property
    def containers(self) -> Global___ListContainersResponse: ...
    @_builtins.property
    def backups(self) -> Global___BrowseBackupsResponse: ...
    @_builtins.property
    def archive(self) -> Global___GetArchiveResponse: ...
    @_builtins.property
    def cancel_job(self) -> Global___CancelJobResponse: ...
    @_builtins.property
    def preview_extraction(self) -> Global___PreviewExtractionResponse: ...
    @_builtins.property
    def release_archive(self) -> Global___ReleaseArchiveResponse: ...
    @_builtins.property
    def list_archives(self) -> Global___ListArchivesResponse: ...
    def __init__(
        self,
        *,
        status: Global___GetStatusResponse | None = ...,
        configuration: Global___GetConfigurationResponse | None = ...,
        save_configuration: Global___SaveConfigurationResponse | None = ...,
        sets: Global___ListSetsResponse | None = ...,
        save_set: Global___SaveSetResponse | None = ...,
        delete_set: Global___DeleteSetResponse | None = ...,
        start_operation: Global___StartOperationResponse | None = ...,
        job: Global___GetJobResponse | None = ...,
        directories: Global___BrowseDirectoriesResponse | None = ...,
        events: Global___JobEvents | None = ...,
        error: Global___BrokerError | None = ...,
        containers: Global___ListContainersResponse | None = ...,
        backups: Global___BrowseBackupsResponse | None = ...,
        archive: Global___GetArchiveResponse | None = ...,
        cancel_job: Global___CancelJobResponse | None = ...,
        preview_extraction: Global___PreviewExtractionResponse | None = ...,
        release_archive: Global___ReleaseArchiveResponse | None = ...,
        list_archives: Global___ListArchivesResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["archive", b"archive", "backups", b"backups", "cancel_job", b"cancel_job", "configuration", b"configuration", "containers", b"containers", "delete_set", b"delete_set", "directories", b"directories", "error", b"error", "events", b"events", "job", b"job", "list_archives", b"list_archives", "preview_extraction", b"preview_extraction", "release_archive", b"release_archive", "response", b"response", "save_configuration", b"save_configuration", "save_set", b"save_set", "sets", b"sets", "start_operation", b"start_operation", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["archive", b"archive", "backups", b"backups", "cancel_job", b"cancel_job", "configuration", b"configuration", "containers", b"containers", "delete_set", b"delete_set", "directories", b"directories", "error", b"error", "events", b"events", "job", b"job", "list_archives", b"list_archives", "preview_extraction", b"preview_extraction", "release_archive", b"release_archive", "response", b"response", "save_configuration", b"save_configuration", "save_set", b"save_set", "sets", b"sets", "start_operation", b"start_operation", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["status", "configuration", "save_configuration", "sets", "save_set", "delete_set", "start_operation", "job", "directories", "events", "error", "containers", "backups", "archive", "cancel_job", "preview_extraction", "release_archive", "list_archives"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___BrokerResponse: _TypeAlias = BrokerResponse  # noqa: Y015

@_typing.final
class JobEvents(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOBS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def jobs(self) -> _containers.RepeatedCompositeFieldContainer[Global___Job]: ...
    def __init__(
        self,
        *,
        jobs: _abc.Iterable[Global___Job] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["jobs", b"jobs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JobEvents: _TypeAlias = JobEvents  # noqa: Y015

@_typing.final
class BrokerError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    message: _builtins.str
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BrokerError: _TypeAlias = BrokerError  # noqa: Y015

@_typing.final
class FailureDetail(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FailureDetail: _TypeAlias = FailureDetail  # noqa: Y015
