# Generated from protondrive_api/v1/control.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .control_pb2 import BrowseBackupsRequest, BrowseBackupsResponse, BrowseDirectoriesRequest, BrowseDirectoriesResponse, CancelJobRequest, CancelJobResponse, DeleteSetRequest, DeleteSetResponse, GetArchiveRequest, GetArchiveResponse, GetConfigurationRequest, GetConfigurationResponse, GetJobRequest, GetJobResponse, GetStatusRequest, GetStatusResponse, ListArchivesRequest, ListArchivesResponse, ListContainersRequest, ListContainersResponse, ListSetsRequest, ListSetsResponse, PreviewExtractionRequest, PreviewExtractionResponse, ReleaseArchiveRequest, ReleaseArchiveResponse, SaveConfigurationRequest, SaveConfigurationResponse, SaveSetRequest, SaveSetResponse, StartOperationRequest, StartOperationResponse, WatchJobRequest, WatchJobResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class ControlService(Protocol):
    async def get_status(self, request: GetStatusRequest, ctx: RequestContext[GetStatusRequest, GetStatusResponse], /) -> GetStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_configuration(self, request: GetConfigurationRequest, ctx: RequestContext[GetConfigurationRequest, GetConfigurationResponse], /) -> GetConfigurationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def save_configuration(self, request: SaveConfigurationRequest, ctx: RequestContext[SaveConfigurationRequest, SaveConfigurationResponse], /) -> SaveConfigurationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_sets(self, request: ListSetsRequest, ctx: RequestContext[ListSetsRequest, ListSetsResponse], /) -> ListSetsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def save_set(self, request: SaveSetRequest, ctx: RequestContext[SaveSetRequest, SaveSetResponse], /) -> SaveSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_set(self, request: DeleteSetRequest, ctx: RequestContext[DeleteSetRequest, DeleteSetResponse], /) -> DeleteSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def start_operation(self, request: StartOperationRequest, ctx: RequestContext[StartOperationRequest, StartOperationResponse], /) -> StartOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_job(self, request: GetJobRequest, ctx: RequestContext[GetJobRequest, GetJobResponse], /) -> GetJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def watch_job(self, request: WatchJobRequest, ctx: RequestContext[WatchJobRequest, WatchJobResponse], /) -> AsyncIterator[WatchJobResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def browse_directories(self, request: BrowseDirectoriesRequest, ctx: RequestContext[BrowseDirectoriesRequest, BrowseDirectoriesResponse], /) -> BrowseDirectoriesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_containers(self, request: ListContainersRequest, ctx: RequestContext[ListContainersRequest, ListContainersResponse], /) -> ListContainersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def browse_backups(self, request: BrowseBackupsRequest, ctx: RequestContext[BrowseBackupsRequest, BrowseBackupsResponse], /) -> BrowseBackupsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_archive(self, request: GetArchiveRequest, ctx: RequestContext[GetArchiveRequest, GetArchiveResponse], /) -> GetArchiveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def cancel_job(self, request: CancelJobRequest, ctx: RequestContext[CancelJobRequest, CancelJobResponse], /) -> CancelJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def preview_extraction(self, request: PreviewExtractionRequest, ctx: RequestContext[PreviewExtractionRequest, PreviewExtractionResponse], /) -> PreviewExtractionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def release_archive(self, request: ReleaseArchiveRequest, ctx: RequestContext[ReleaseArchiveRequest, ReleaseArchiveResponse], /) -> ReleaseArchiveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_archives(self, request: ListArchivesRequest, ctx: RequestContext[ListArchivesRequest, ListArchivesResponse], /) -> ListArchivesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ControlServiceASGIApplication(ConnectASGIApplication[ControlService]):
    def __init__(
        self,
        service: ControlService | AsyncGenerator[ControlService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/protondrive_api.v1.ControlService/GetStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStatus",
                        service_name="protondrive_api.v1.ControlService",
                        input=GetStatusRequest,
                        output=GetStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_status,
                ),
                "/protondrive_api.v1.ControlService/GetConfiguration": Endpoint.unary(
                    method=MethodInfo(
                        name="GetConfiguration",
                        service_name="protondrive_api.v1.ControlService",
                        input=GetConfigurationRequest,
                        output=GetConfigurationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_configuration,
                ),
                "/protondrive_api.v1.ControlService/SaveConfiguration": Endpoint.unary(
                    method=MethodInfo(
                        name="SaveConfiguration",
                        service_name="protondrive_api.v1.ControlService",
                        input=SaveConfigurationRequest,
                        output=SaveConfigurationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.save_configuration,
                ),
                "/protondrive_api.v1.ControlService/ListSets": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSets",
                        service_name="protondrive_api.v1.ControlService",
                        input=ListSetsRequest,
                        output=ListSetsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_sets,
                ),
                "/protondrive_api.v1.ControlService/SaveSet": Endpoint.unary(
                    method=MethodInfo(
                        name="SaveSet",
                        service_name="protondrive_api.v1.ControlService",
                        input=SaveSetRequest,
                        output=SaveSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.save_set,
                ),
                "/protondrive_api.v1.ControlService/DeleteSet": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteSet",
                        service_name="protondrive_api.v1.ControlService",
                        input=DeleteSetRequest,
                        output=DeleteSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_set,
                ),
                "/protondrive_api.v1.ControlService/StartOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="StartOperation",
                        service_name="protondrive_api.v1.ControlService",
                        input=StartOperationRequest,
                        output=StartOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.start_operation,
                ),
                "/protondrive_api.v1.ControlService/GetJob": Endpoint.unary(
                    method=MethodInfo(
                        name="GetJob",
                        service_name="protondrive_api.v1.ControlService",
                        input=GetJobRequest,
                        output=GetJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_job,
                ),
                "/protondrive_api.v1.ControlService/WatchJob": Endpoint.server_stream(
                    method=MethodInfo(
                        name="WatchJob",
                        service_name="protondrive_api.v1.ControlService",
                        input=WatchJobRequest,
                        output=WatchJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch_job,
                ),
                "/protondrive_api.v1.ControlService/BrowseDirectories": Endpoint.unary(
                    method=MethodInfo(
                        name="BrowseDirectories",
                        service_name="protondrive_api.v1.ControlService",
                        input=BrowseDirectoriesRequest,
                        output=BrowseDirectoriesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.browse_directories,
                ),
                "/protondrive_api.v1.ControlService/ListContainers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListContainers",
                        service_name="protondrive_api.v1.ControlService",
                        input=ListContainersRequest,
                        output=ListContainersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_containers,
                ),
                "/protondrive_api.v1.ControlService/BrowseBackups": Endpoint.unary(
                    method=MethodInfo(
                        name="BrowseBackups",
                        service_name="protondrive_api.v1.ControlService",
                        input=BrowseBackupsRequest,
                        output=BrowseBackupsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.browse_backups,
                ),
                "/protondrive_api.v1.ControlService/GetArchive": Endpoint.unary(
                    method=MethodInfo(
                        name="GetArchive",
                        service_name="protondrive_api.v1.ControlService",
                        input=GetArchiveRequest,
                        output=GetArchiveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_archive,
                ),
                "/protondrive_api.v1.ControlService/CancelJob": Endpoint.unary(
                    method=MethodInfo(
                        name="CancelJob",
                        service_name="protondrive_api.v1.ControlService",
                        input=CancelJobRequest,
                        output=CancelJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.cancel_job,
                ),
                "/protondrive_api.v1.ControlService/PreviewExtraction": Endpoint.unary(
                    method=MethodInfo(
                        name="PreviewExtraction",
                        service_name="protondrive_api.v1.ControlService",
                        input=PreviewExtractionRequest,
                        output=PreviewExtractionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.preview_extraction,
                ),
                "/protondrive_api.v1.ControlService/ReleaseArchive": Endpoint.unary(
                    method=MethodInfo(
                        name="ReleaseArchive",
                        service_name="protondrive_api.v1.ControlService",
                        input=ReleaseArchiveRequest,
                        output=ReleaseArchiveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.release_archive,
                ),
                "/protondrive_api.v1.ControlService/ListArchives": Endpoint.unary(
                    method=MethodInfo(
                        name="ListArchives",
                        service_name="protondrive_api.v1.ControlService",
                        input=ListArchivesRequest,
                        output=ListArchivesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_archives,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/protondrive_api.v1.ControlService"


class ControlServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_status(
        self,
        request: GetStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStatus",
                service_name="protondrive_api.v1.ControlService",
                input=GetStatusRequest,
                output=GetStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_configuration(
        self,
        request: GetConfigurationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetConfigurationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetConfiguration",
                service_name="protondrive_api.v1.ControlService",
                input=GetConfigurationRequest,
                output=GetConfigurationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def save_configuration(
        self,
        request: SaveConfigurationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SaveConfigurationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SaveConfiguration",
                service_name="protondrive_api.v1.ControlService",
                input=SaveConfigurationRequest,
                output=SaveConfigurationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_sets(
        self,
        request: ListSetsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListSetsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSets",
                service_name="protondrive_api.v1.ControlService",
                input=ListSetsRequest,
                output=ListSetsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def save_set(
        self,
        request: SaveSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SaveSetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SaveSet",
                service_name="protondrive_api.v1.ControlService",
                input=SaveSetRequest,
                output=SaveSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_set(
        self,
        request: DeleteSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteSetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSet",
                service_name="protondrive_api.v1.ControlService",
                input=DeleteSetRequest,
                output=DeleteSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def start_operation(
        self,
        request: StartOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> StartOperationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartOperation",
                service_name="protondrive_api.v1.ControlService",
                input=StartOperationRequest,
                output=StartOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_job(
        self,
        request: GetJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetJobResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJob",
                service_name="protondrive_api.v1.ControlService",
                input=GetJobRequest,
                output=GetJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch_job(
        self,
        request: WatchJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[WatchJobResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchJob",
                service_name="protondrive_api.v1.ControlService",
                input=WatchJobRequest,
                output=WatchJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def browse_directories(
        self,
        request: BrowseDirectoriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> BrowseDirectoriesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BrowseDirectories",
                service_name="protondrive_api.v1.ControlService",
                input=BrowseDirectoriesRequest,
                output=BrowseDirectoriesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_containers(
        self,
        request: ListContainersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListContainersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListContainers",
                service_name="protondrive_api.v1.ControlService",
                input=ListContainersRequest,
                output=ListContainersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def browse_backups(
        self,
        request: BrowseBackupsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> BrowseBackupsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BrowseBackups",
                service_name="protondrive_api.v1.ControlService",
                input=BrowseBackupsRequest,
                output=BrowseBackupsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_archive(
        self,
        request: GetArchiveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetArchiveResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetArchive",
                service_name="protondrive_api.v1.ControlService",
                input=GetArchiveRequest,
                output=GetArchiveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def cancel_job(
        self,
        request: CancelJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> CancelJobResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelJob",
                service_name="protondrive_api.v1.ControlService",
                input=CancelJobRequest,
                output=CancelJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def preview_extraction(
        self,
        request: PreviewExtractionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PreviewExtractionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PreviewExtraction",
                service_name="protondrive_api.v1.ControlService",
                input=PreviewExtractionRequest,
                output=PreviewExtractionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def release_archive(
        self,
        request: ReleaseArchiveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ReleaseArchiveResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseArchive",
                service_name="protondrive_api.v1.ControlService",
                input=ReleaseArchiveRequest,
                output=ReleaseArchiveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_archives(
        self,
        request: ListArchivesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListArchivesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListArchives",
                service_name="protondrive_api.v1.ControlService",
                input=ListArchivesRequest,
                output=ListArchivesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ControlServiceSync(Protocol):
    def get_status(self, request: GetStatusRequest, ctx: RequestContext[GetStatusRequest, GetStatusResponse], /) -> GetStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_configuration(self, request: GetConfigurationRequest, ctx: RequestContext[GetConfigurationRequest, GetConfigurationResponse], /) -> GetConfigurationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def save_configuration(self, request: SaveConfigurationRequest, ctx: RequestContext[SaveConfigurationRequest, SaveConfigurationResponse], /) -> SaveConfigurationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_sets(self, request: ListSetsRequest, ctx: RequestContext[ListSetsRequest, ListSetsResponse], /) -> ListSetsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def save_set(self, request: SaveSetRequest, ctx: RequestContext[SaveSetRequest, SaveSetResponse], /) -> SaveSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_set(self, request: DeleteSetRequest, ctx: RequestContext[DeleteSetRequest, DeleteSetResponse], /) -> DeleteSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def start_operation(self, request: StartOperationRequest, ctx: RequestContext[StartOperationRequest, StartOperationResponse], /) -> StartOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_job(self, request: GetJobRequest, ctx: RequestContext[GetJobRequest, GetJobResponse], /) -> GetJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def watch_job(self, request: WatchJobRequest, ctx: RequestContext[WatchJobRequest, WatchJobResponse], /) -> Iterator[WatchJobResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def browse_directories(self, request: BrowseDirectoriesRequest, ctx: RequestContext[BrowseDirectoriesRequest, BrowseDirectoriesResponse], /) -> BrowseDirectoriesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_containers(self, request: ListContainersRequest, ctx: RequestContext[ListContainersRequest, ListContainersResponse], /) -> ListContainersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def browse_backups(self, request: BrowseBackupsRequest, ctx: RequestContext[BrowseBackupsRequest, BrowseBackupsResponse], /) -> BrowseBackupsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_archive(self, request: GetArchiveRequest, ctx: RequestContext[GetArchiveRequest, GetArchiveResponse], /) -> GetArchiveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def cancel_job(self, request: CancelJobRequest, ctx: RequestContext[CancelJobRequest, CancelJobResponse], /) -> CancelJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def preview_extraction(self, request: PreviewExtractionRequest, ctx: RequestContext[PreviewExtractionRequest, PreviewExtractionResponse], /) -> PreviewExtractionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def release_archive(self, request: ReleaseArchiveRequest, ctx: RequestContext[ReleaseArchiveRequest, ReleaseArchiveResponse], /) -> ReleaseArchiveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_archives(self, request: ListArchivesRequest, ctx: RequestContext[ListArchivesRequest, ListArchivesResponse], /) -> ListArchivesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ControlServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ControlServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/protondrive_api.v1.ControlService/GetStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetStatus",
                        service_name="protondrive_api.v1.ControlService",
                        input=GetStatusRequest,
                        output=GetStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_status,
                ),
                "/protondrive_api.v1.ControlService/GetConfiguration": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetConfiguration",
                        service_name="protondrive_api.v1.ControlService",
                        input=GetConfigurationRequest,
                        output=GetConfigurationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_configuration,
                ),
                "/protondrive_api.v1.ControlService/SaveConfiguration": EndpointSync.unary(
                    method=MethodInfo(
                        name="SaveConfiguration",
                        service_name="protondrive_api.v1.ControlService",
                        input=SaveConfigurationRequest,
                        output=SaveConfigurationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.save_configuration,
                ),
                "/protondrive_api.v1.ControlService/ListSets": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSets",
                        service_name="protondrive_api.v1.ControlService",
                        input=ListSetsRequest,
                        output=ListSetsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_sets,
                ),
                "/protondrive_api.v1.ControlService/SaveSet": EndpointSync.unary(
                    method=MethodInfo(
                        name="SaveSet",
                        service_name="protondrive_api.v1.ControlService",
                        input=SaveSetRequest,
                        output=SaveSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.save_set,
                ),
                "/protondrive_api.v1.ControlService/DeleteSet": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteSet",
                        service_name="protondrive_api.v1.ControlService",
                        input=DeleteSetRequest,
                        output=DeleteSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_set,
                ),
                "/protondrive_api.v1.ControlService/StartOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="StartOperation",
                        service_name="protondrive_api.v1.ControlService",
                        input=StartOperationRequest,
                        output=StartOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.start_operation,
                ),
                "/protondrive_api.v1.ControlService/GetJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetJob",
                        service_name="protondrive_api.v1.ControlService",
                        input=GetJobRequest,
                        output=GetJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_job,
                ),
                "/protondrive_api.v1.ControlService/WatchJob": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="WatchJob",
                        service_name="protondrive_api.v1.ControlService",
                        input=WatchJobRequest,
                        output=WatchJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch_job,
                ),
                "/protondrive_api.v1.ControlService/BrowseDirectories": EndpointSync.unary(
                    method=MethodInfo(
                        name="BrowseDirectories",
                        service_name="protondrive_api.v1.ControlService",
                        input=BrowseDirectoriesRequest,
                        output=BrowseDirectoriesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.browse_directories,
                ),
                "/protondrive_api.v1.ControlService/ListContainers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListContainers",
                        service_name="protondrive_api.v1.ControlService",
                        input=ListContainersRequest,
                        output=ListContainersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_containers,
                ),
                "/protondrive_api.v1.ControlService/BrowseBackups": EndpointSync.unary(
                    method=MethodInfo(
                        name="BrowseBackups",
                        service_name="protondrive_api.v1.ControlService",
                        input=BrowseBackupsRequest,
                        output=BrowseBackupsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.browse_backups,
                ),
                "/protondrive_api.v1.ControlService/GetArchive": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetArchive",
                        service_name="protondrive_api.v1.ControlService",
                        input=GetArchiveRequest,
                        output=GetArchiveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_archive,
                ),
                "/protondrive_api.v1.ControlService/CancelJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="CancelJob",
                        service_name="protondrive_api.v1.ControlService",
                        input=CancelJobRequest,
                        output=CancelJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.cancel_job,
                ),
                "/protondrive_api.v1.ControlService/PreviewExtraction": EndpointSync.unary(
                    method=MethodInfo(
                        name="PreviewExtraction",
                        service_name="protondrive_api.v1.ControlService",
                        input=PreviewExtractionRequest,
                        output=PreviewExtractionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.preview_extraction,
                ),
                "/protondrive_api.v1.ControlService/ReleaseArchive": EndpointSync.unary(
                    method=MethodInfo(
                        name="ReleaseArchive",
                        service_name="protondrive_api.v1.ControlService",
                        input=ReleaseArchiveRequest,
                        output=ReleaseArchiveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.release_archive,
                ),
                "/protondrive_api.v1.ControlService/ListArchives": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListArchives",
                        service_name="protondrive_api.v1.ControlService",
                        input=ListArchivesRequest,
                        output=ListArchivesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_archives,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/protondrive_api.v1.ControlService"


class ControlServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def get_status(
        self,
        request: GetStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStatus",
                service_name="protondrive_api.v1.ControlService",
                input=GetStatusRequest,
                output=GetStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_configuration(
        self,
        request: GetConfigurationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetConfigurationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetConfiguration",
                service_name="protondrive_api.v1.ControlService",
                input=GetConfigurationRequest,
                output=GetConfigurationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def save_configuration(
        self,
        request: SaveConfigurationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SaveConfigurationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SaveConfiguration",
                service_name="protondrive_api.v1.ControlService",
                input=SaveConfigurationRequest,
                output=SaveConfigurationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_sets(
        self,
        request: ListSetsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListSetsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSets",
                service_name="protondrive_api.v1.ControlService",
                input=ListSetsRequest,
                output=ListSetsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def save_set(
        self,
        request: SaveSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SaveSetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SaveSet",
                service_name="protondrive_api.v1.ControlService",
                input=SaveSetRequest,
                output=SaveSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_set(
        self,
        request: DeleteSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DeleteSetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSet",
                service_name="protondrive_api.v1.ControlService",
                input=DeleteSetRequest,
                output=DeleteSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def start_operation(
        self,
        request: StartOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> StartOperationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartOperation",
                service_name="protondrive_api.v1.ControlService",
                input=StartOperationRequest,
                output=StartOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_job(
        self,
        request: GetJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetJobResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJob",
                service_name="protondrive_api.v1.ControlService",
                input=GetJobRequest,
                output=GetJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def watch_job(
        self,
        request: WatchJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[WatchJobResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchJob",
                service_name="protondrive_api.v1.ControlService",
                input=WatchJobRequest,
                output=WatchJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def browse_directories(
        self,
        request: BrowseDirectoriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> BrowseDirectoriesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BrowseDirectories",
                service_name="protondrive_api.v1.ControlService",
                input=BrowseDirectoriesRequest,
                output=BrowseDirectoriesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_containers(
        self,
        request: ListContainersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListContainersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListContainers",
                service_name="protondrive_api.v1.ControlService",
                input=ListContainersRequest,
                output=ListContainersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def browse_backups(
        self,
        request: BrowseBackupsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> BrowseBackupsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BrowseBackups",
                service_name="protondrive_api.v1.ControlService",
                input=BrowseBackupsRequest,
                output=BrowseBackupsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_archive(
        self,
        request: GetArchiveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetArchiveResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetArchive",
                service_name="protondrive_api.v1.ControlService",
                input=GetArchiveRequest,
                output=GetArchiveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def cancel_job(
        self,
        request: CancelJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> CancelJobResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelJob",
                service_name="protondrive_api.v1.ControlService",
                input=CancelJobRequest,
                output=CancelJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def preview_extraction(
        self,
        request: PreviewExtractionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PreviewExtractionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PreviewExtraction",
                service_name="protondrive_api.v1.ControlService",
                input=PreviewExtractionRequest,
                output=PreviewExtractionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def release_archive(
        self,
        request: ReleaseArchiveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ReleaseArchiveResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseArchive",
                service_name="protondrive_api.v1.ControlService",
                input=ReleaseArchiveRequest,
                output=ReleaseArchiveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_archives(
        self,
        request: ListArchivesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListArchivesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListArchives",
                service_name="protondrive_api.v1.ControlService",
                input=ListArchivesRequest,
                output=ListArchivesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
