"""Operations the backup service needs from a remote storage backend."""

from pathlib import Path
from typing import Protocol, runtime_checkable

from .models import AuthStatus, RemoteEntry, TransferStatus


class RemoteFiles(Protocol):
    def list(self, path: str) -> list[RemoteEntry]: ...
    def upload(self, path: str | Path, folder: str) -> None: ...
    def download(self, remote: str, directory: str | Path) -> None: ...
    def trash(self, folder: str, entry: RemoteEntry) -> None: ...


class StorageBackend(RemoteFiles, Protocol):
    def probe(self) -> AuthStatus: ...
    def status(self) -> AuthStatus: ...
    def probe_failed(self, error: str) -> AuthStatus: ...
    def authentication_in_progress(self) -> bool: ...
    def start_auth(self) -> AuthStatus: ...
    def cancel_auth(self) -> AuthStatus: ...
    def logout(self) -> AuthStatus: ...
    def transfer_status(self) -> TransferStatus: ...
    def cancel_transfer(self, force: bool = False) -> None: ...
    def ensure_folder(self, path: str) -> None: ...
    def ensure_instance_owned(self) -> None: ...


@runtime_checkable
class CliLockRepair(Protocol):
    def repair_lock(self) -> dict[str, str | bool]: ...
